### ISSUE TITLE
TypeError: Cannot read property 'length' in /establishment/:estid/beer_statuses

### ISSUE THREAD

**Issue by pagan8** [AthensWorks/OBWapp-API#15]
/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'length' of undefined
    at Query._callback (/home/hacknight/brew-prod-test/OBWapp-API/express-app/brew.js:195:24)
    at Query.Sequence.end (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)

offending code appears to be the for loop.. 

app.get('/establishment/:estid/beer_statuses', function (req, res) {
  res.type('json');
  var sql = "SELECT * FROM statuses WHERE statuses.establishment_id = " + req.params.estid + ";";
  connection.query(sql, function (err, rows) {
          var beer_statuses = [];
          for (i = 0; i < rows.length; i++) {
                  beer_statuses.push({ id: rows[i].beer_id, status: beer_status_names[rows[i].status] });
          }
          res.json({ beer_statuses: beer_statuses });
  });
});

**Comment by pagan8** [comment]
Happened again... 


/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'length' of undefined
    at Query._callback (/home/hacknight/brew-prod-test/OBWapp-API/express-app/brew.js:195:24)
    at Query.Sequence.end (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/hacknight/brew-prod-test/OBWapp-API/express-app/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)

**Comment by pagan8** [comment]
I was able to reproduce the problem, it occurs when an invalid sequence is dropped in for establishment id:


  723  curl -X GET http://173.230.142.215:3000/establishment/1/beer_statuses
  724  curl -X GET http://173.230.142.215:3000/establishment/2/beer_statuses
  725  curl -X GET http://173.230.142.215:3000/establishment/3/beer_statuses
  726  curl -X GET http://173.230.142.215:3000/establishment/7/beer_statuses
  727  curl -X GET http://173.230.142.215:3000/establishment/9/beer_statuses
  728  curl -X GET http://173.230.142.215:3000/establishment/4/beer_statuses
  729  curl -X GET http://173.230.142.215:3000/establishment/55/beer_statuses
  730  curl -X GET http://173.230.142.215:3000/establishment/A/beer_statuses
  731  curl -X GET http://173.230.142.215:3000/establishment/A/beer_statuses
  732  curl -X GET http://173.230.142.215:3000/establishment/A/beer_statuses

730 - 732 cause the problem...

I fixed it by doing this:


          if (!err) {
              for (i = 0; i < rows.length; i++) {
                      beer_statuses.push({ id: rows[i].beer_id, status: beer_status_names[rows[i].status] });
              }
              res.json({ beer_statuses: beer_statuses });
          } else {
              res.sendStatus(404);
          }
